import type { ModelDefinition } from "@/models.js";

export const bytedanceModels = [
	{
		id: "doubao-seed-1-6-250615",
		name: "Doubao Seed 1.6 (250615)",
		description:
			"ByteDance Seed 1.6 vision model with thinking/non-thinking modes, multimodal inputs, and 256K context window",
		family: "bytedance",
		releasedAt: new Date("2025-06-25"),
		providers: [
			{
				providerId: "bytedance",
				modelName: "doubao-seed-1-6-250615",
				inputPrice: 0.00025 / 1000,
				outputPrice: 0.002 / 1000,
				cachedInputPrice: 0.00005 / 1000,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "doubao-seed-1-6-250915",
		name: "Doubao Seed 1.6 (250915)",
		description:
			"ByteDance Seed 1.6 vision model released September 15, 2025 with thinking/non-thinking modes and multimodal inputs",
		family: "bytedance",
		releasedAt: new Date("2025-09-15"),
		providers: [
			{
				providerId: "bytedance",
				modelName: "doubao-seed-1-6-250915",
				inputPrice: 0.00025 / 1000,
				cachedInputPrice: 0.00005 / 1000,
				outputPrice: 0.002 / 1000,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "doubao-seed-1-6-flash-250828",
		name: "Doubao Seed 1.6 Flash (250828)",
		description:
			"Doubao Seed 1.6 Flash - faster, cost-effective vision model released July 15, 2025",
		family: "bytedance",
		releasedAt: new Date("2025-08-29"),
		providers: [
			{
				providerId: "bytedance",
				modelName: "doubao-seed-1-6-flash-250828",
				inputPrice: 0.00007 / 1000,
				cachedInputPrice: 0.000015 / 1000,
				outputPrice: 0.0003 / 1000,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "tuzi",
				modelName: "doubao-seed-1-6-flash-250828",
				inputPrice: 6.0 / 1e6,
				outputPrice: 42.0 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "doubao-seed-1-8-251228",
		name: "Seed 1.8 (251228)",
		description:
			"ByteDance Seed 1.8 advanced vision model released December 28, 2025 with enhanced capabilities",
		family: "bytedance",
		releasedAt: new Date("2025-12-18"),
		providers: [
			{
				providerId: "bytedance",
				modelName: "doubao-seed-1-8-251228",
				inputPrice: 0.00025 / 1000,
				cachedInputPrice: 0.00005 / 1000,
				outputPrice: 0.002 / 1000,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "doubao-seed-2-0-mini-260215",
		name: "Seed 2.0 Mini (260215)",
		description:
			"ByteDance Seed 2.0 advanced vision model released with enhanced capabilities",
		family: "bytedance",
		releasedAt: new Date("2026-02-15"),
		providers: [
			{
				providerId: "bytedance",
				modelName: "doubao-seed-2-0-mini-260215",
				inputPrice: 0.2 / 7 / 1e6,
				cachedInputPrice: 0.04 / 7 / 1e6,
				outputPrice: 2 / 7 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "doubao-seed-2-0-lite-260215",
		name: "Seed 2.0 Lite (260215)",
		description:
			"ByteDance Seed 2.0 advanced vision model released with enhanced capabilities",
		family: "bytedance",
		releasedAt: new Date("2026-02-15"),
		providers: [
			{
				providerId: "bytedance",
				modelName: "doubao-seed-2-0-lite-260215",
				inputPrice: 0.6 / 7 / 1e6,
				cachedInputPrice: 0.12 / 7 / 1e6,
				outputPrice: 3.6 / 7 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "doubao-seed-2-0-pro-260215",
		name: "Seed 2.0 Pro (260215)",
		description:
			"ByteDance Seed 2.0 advanced vision model released with enhanced capabilities",
		family: "bytedance",
		releasedAt: new Date("2026-02-15"),
		providers: [
			{
				providerId: "bytedance",
				modelName: "doubao-seed-2-0-pro-260215",
				inputPrice: 3.2 / 7 / 1e6,
				cachedInputPrice: 0.64 / 7 / 1e6,
				outputPrice: 16 / 7 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "doubao-seed-2-0-code-260215",
		name: "Seed 2.0 Code (260215)",
		description:
			"ByteDance Seed 2.0 advanced vision model released with enhanced capabilities",
		family: "bytedance",
		releasedAt: new Date("2026-02-15"),
		providers: [
			{
				providerId: "bytedance",
				modelName: "doubao-seed-2-0-code-preview-260215",
				inputPrice: 3.2 / 7 / 1e6,
				cachedInputPrice: 0.64 / 7 / 1e6,
				outputPrice: 16 / 7 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "doubao-seedream-5-0-260128",
		name: "Doubao Seedream 5.0 (260128)",
		description: "ByteDance Seedream 5.0 text-to-image generation model.",
		family: "bytedance",
		output: ["text", "image"],
		releasedAt: new Date("2026-01-28"),
		providers: [
			{
				test: "skip",
				providerId: "bytedance",
				modelName: "doubao-seedream-5-0-260128",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0.04,
				discount: 0.1,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: false,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
			{
				test: "skip",
				providerId: "tuzi",
				modelName: "doubao-seedream-5-0-260128",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0.01,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: false,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
		],
	},
	{
		id: "doubao-seedream-4-0",
		name: "Doubao Seedream 4.0",
		description:
			"ByteDance Seedream 4.0 text-to-image generation model with high-quality visual output",
		family: "bytedance",
		output: ["text", "image"],
		releasedAt: new Date("2025-09-16"),
		providers: [
			{
				test: "skip",
				providerId: "bytedance",
				modelName: "doubao-seedream-4-0-250828",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0.035,
				discount: 0.1,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: false,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
			{
				test: "skip",
				providerId: "tuzi",
				modelName: "doubao-seedream-4-0-250828",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0.02,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: false,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
		],
	},
	{
		id: "doubao-seedream-4-5",
		name: "Doubao Seedream 4.5",
		description:
			"ByteDance Seedream 4.5 advanced text-to-image generation model with enhanced quality and consistency",
		family: "bytedance",
		output: ["text", "image"],
		releasedAt: new Date("2025-12-03"),
		providers: [
			{
				test: "skip",
				providerId: "bytedance",
				modelName: "doubao-seedream-4-5-251128",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0.045,
				discount: 0.1,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: false,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
			{
				test: "skip",
				providerId: "tuzi",
				modelName: "doubao-seedream-4-5-251128",
				inputPrice: 0.0 / 1e6,
				outputPrice: 0.0 / 1e6,
				requestPrice: 0.0172,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: false,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
