name: Build Images

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: [arc-runner]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        app: [api, gateway, ui, admin, worker]
        platform: [linux/amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver-opts: image=registry.deemos.com/library/buildkit:buildx-stable-1

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.deemos.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            HTTP_PROXY=http://10.219.33.6:12388
            HTTPS_PROXY=http://10.219.33.6:12388
          context: .
          file: infra/split.dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          cache-to: type=registry,ref=registry.deemos.com/deemos/llmgateway-${{ matrix.app }}:buildcache
          cache-from: type=registry,ref=registry.deemos.com/deemos/llmgateway-${{ matrix.app }}:buildcache
          target: ${{ matrix.app }}
          tags: |
            registry.deemos.com/deemos/llmgateway-${{ matrix.app }}:latest
            registry.deemos.com/deemos/llmgateway-${{ matrix.app }}:1.0.${{ github.run_number }}